sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov

script:
  - pytest tests
  - pytest --cov sequeval

after_success:
  - pip install codecov
  - codecov